name: SFU Timetable Monitor

on:
  schedule:
    - cron: '*/10 6-23 * * *'  # Каждые 10 минут с 6:00 до 23:00
  workflow_dispatch:            # Возможность запустить вручную

jobs:
  check-timetable:
    runs-on: ubuntu-latest
    steps:
      - name: Проверяем, появилось ли расписание
        id: check
        run: |
          # Делаем запрос к автозаполнению по "ки"
          response=$(curl -s "https://edu.sfu-kras.ru/timetable/groups/autocomplete/%D0%BA%D0%B823")
          echo "Ответ от API: $response"
          
          # Если в ответе есть запятая — значит, есть группы (расписание выложено)
          if [[ "$response" == *","* ]]; then
            echo "timetable_found=true" >> $GITHUB_ENV
            echo "✅ Расписание найдено! Отправляем уведомление."
          else
            echo "Расписание ещё не доступно."
            exit 1  # Прерываем job, но не workflow — чтобы продолжал проверять
          fi

      - name: Отправляем уведомление в Telegram
        if: env.timetable_found == 'true'
        run: |
          url="https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
          message="🎉 Расписание для групп КИ выложено!👉 https://edu.sfu-kras.ru/timetable"
          response=$(curl -s -X POST "$url" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$message" \
            -d disable_notification=false)
          
          echo "Ответ Telegram: $response"
          
          if echo "$response" | grep -q '"ok":false'; then
            echo "❌ Ошибка отправки уведомления"
            exit 1
          fi

      - name: Отключаем workflow после успешной отправки
        if: env.timetable_found == 'true'
        run: |
          echo "Отключаем workflow, чтобы не запускался снова..."
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/timetable-monitor.yml/disable"
